fix: fix a bug that ghd2i fails if assingees is nil
https://github.com/suzuki-shunsuke/ghd2i/actions/runs/12137201868/job/33839927137?pr=25

```
time=2024-12-03T09:58:33Z level=error msg=handle a discussion env=linux/amd64 error=create an Issue: POST https://api.github.com/repos/suzuki-shunsuke/test-ghd2i/issues: 422 Invalid request.

For 'properties/assignees', nil is not an array. [] program=ghd2i version=
time=2024-12-03T09:58:33Z level=fatal msg=ghd2i failed env=linux/amd64 error=failed to handle some discussions program=ghd2i version=
Error: Process completed with exit code 1.
```